server:
  port: ${PORT:8080}

spring:
  application:
    name: dscommerce

  profiles:
    active: ${APP_PROFILE:test}

  jpa:
    open-in-view: false

# Spring Security
security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    secret: ${JWT_SECRET:myjwtsecret}
    duration: ${JWT_DURATION:86400} # 86400 = Equivalente a 1 dia

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

---
spring:
  config:
    activate:
      on-profile: test

  # --- DATASOURCE (H2) ---
  datasource:
    url: jdbc:h2:mem:dscommerce_db
    username: dev
    password:
    driver-class-name: org.h2.Driver

  # --- H2 CONSOLE WEB ---
  h2:
    console:
      enabled: true
      path: /h2-console

  # --- JPA / HIBERNATE ---
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # Alterado de update para create-drop
    show-sql: true
    init:
      mode: always
    properties:
      hibernate:
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5433/dscommerce
    username: postgres
    password: 1234567

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    # ================INSERÇÃO DE DADOS NO BANCO(‘script’ de criação do banco na pasta do projeto)====================
      jakarta:
         persistence:
           schema-generation:
             create-source: metadata
             scripts:
               action: create
               create-target: create.sql

      hbm2ddl:
         delimiter: ";"

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true